### PR TITLE
Update to Node.js

### PR DESCRIPTION
**Pull request by samtstern**
cc @codingdoug @abehaskins

### CODE REVIEW

**Comment by atlanteh** [comment]
Isn't updating to flexible environment mean that now there's no free quota, and we'll be charged for event one cron job evrey 24 hours?
According to [these docs](https://cloud.google.com/free/docs/always-free-usage-limits#gae_name):

> Note: The free tier is available only for the Standard Environment.

and these pricing:
https://cloud.google.com/products/calculator/#id=4b0d2eb9-cfee-4a67-8ee4-133c28eb8621
It seems that even 0.1 cpu would not be free..
So why change to flexible env?

**Comment by atlanteh** [comment]
Ah, now I realize that unless env: flex is specified then F1 will be used (which is free for 1 instance).
Just to make sure google doesn't change future defaults and to make sure I don't get charged, I still prefer to be explicit and add:
```
instance_class: F1
automatic_scaling:
  max_instances: 1
```

**Comment by samtstern** [comment]
@atlanteh good point!  Want to send a PR with the change?

**Comment by atlanteh** [comment]
Sure

**Pull request merged**
